/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as PapersPaperIdRouteImport } from './routes/papers/$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/papers/$paperId' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/papers/$paperId' | '/projects/$projectId'
  id: '__root__' | '/' | '/papers/$paperId' | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
